version: '3.2'

services:
  db:
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
  nginx:
    build: nginx
    healthcheck:
      test: 'nc -z localhost 8000 > /dev/null 2>&1 || exit 1'
    ports:
      - 8000
    networks:
      - traefik_proxy
    deploy:
      labels:
        traefik.enable: 'true'
        traefik.backend: nginx
        traefik.frontend.rule: 'Host: cc.roonyx.team'
        traefik.port: '8000'
volumes:
  mysql:
networks:
  traefik_proxy:
    external: true
