version: '3.2'

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  nginx:
    build: nginx
    healthcheck:
      test: 'nc -z localhost 8000 > /dev/null 2>&1 || exit 1'
    ports:
      - 8000
    networks:
      - traefik_proxy
    deploy:
      labels:
        traefik.enable: 'true'
        traefik.backend: nginx
        traefik.frontend.rule: 'Host: cc.roonyx.team'
        traefik.port: '8000'
volumes:
  mysql:
networks:
  traefik_proxy:
    external: true
