version: '3.2'

services:
  db:
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - net
  nginx:
    build: nginx
    healthcheck:
      test: 'nc -z localhost 8000 > /dev/null 2>&1 || exit 1'
    ports:
      - 8000
    networks:
      - traefik_proxy
      - net
    deploy:
      labels:
        traefik.enable: 'true'
        traefik.backend: nginx
        traefik.frontend.rule: 'Host: cc.roonyx.team'
        traefik.port: '8000'
  php:
    networks:
      - net
  php_migrator:
    networks:
      - net
    deploy:
      mode: replicated
      restart_policy:
        condition: none
volumes:
  mysql:
networks:
  net:
  traefik_proxy:
    external: true
