version: '3.2'

services:
  db:
    image: mysql
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: '{{ services.cryptocompose.db.root_password }}'
      MYSQL_DATABASE: '{{ services.head_hunter.db.name }}'
      MYSQL_USER: '{{ services.head_hunter.db.user }}'
      MYSQL_PASSWORD: '{{ services.head_hunter.db.password }}'
  php:
    image: "${REGISTRY}/${CRYPTOCOMPOSE_SERVICE}:${CRYPTOCOMPOSE_SERVICE__VERSION}"
  php_migrator:
    image: "${REGISTRY}/${CRYPTOCOMPOSE_SERVICE}:${CRYPTOCOMPOSE_SERVICE__VERSION}"
    command: sh -c './wait-for db:3306 -- ./bin/console doctrine:migrations:migrate'

  nginx:
    image: "${REGISTRY}/${CRYPTOCOMPOSE__NGINX_SERVICE}:${CRYPTOCOMPOSE__NGINX_SERVICE__VERSION}"
    ports:
      - 80
