version: '3.2'

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - net
  php:
    image: "${REGISTRY}/${CRYPTOCOMPOSE_SERVICE}:${CRYPTOCOMPOSE_SERVICE__VERSION}-development"
    build:
      context: .
      args:
        TIMEZONE: 'Europe/Paris'
    volumes:
      - ./src:/var/www/symfony
    networks:
      - net
  php_migrator:
    image: "${REGISTRY}/${CRYPTOCOMPOSE_SERVICE}:${CRYPTOCOMPOSE_SERVICE__VERSION}-development"
    build:
      context: .
      args:
        TIMEZONE: 'Europe/Paris'
    command: sh -c './wait-for db:3306 -- ./bin/console doctrine:migrations:migrate'
    networks:
      - net
  nginx:
    build:
      dockerfile: nginx/Dockerfile
      context: .
    ports:
      - 80:80
    networks:
      - net
volumes:
  mysql:
networks:
  net:
