<?php

namespace AppBundle\Repository;

/**
 * CoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoinRepository extends \Doctrine\ORM\EntityRepository
{
}
