<?php

namespace AppBundle\Repository;

/**
 * LogCoinRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogCoinRateRepository extends \Doctrine\ORM\EntityRepository
{
}
